const data = {
    products: [
        {
            _id: '1', 
            name: 'Yellow Gamerboy',
            category: 'Electronics',
            image: '/images/yellowgameboy.jpg',
            price: 110,
            brand: 'Wintendo',
            rating: 4.8,
            numReviews: 488,
            description: 'The original Wintendo Gamerboy Color. In yellow!',
        },
        {
            _id: '2', 
            name: 'Blue Gamerboy',
            category: 'Electronics',
            image: '/images/bluegameboy.jpg',
            price: 110,
            brand: 'Wintendo',
            rating: 4.7,
            numReviews: 414,
            description: 'The original Wintendo Gamerboy Color. In blue!',
        },
        {
            _id: '3', 
            name: 'Purple Gamerboy',
            category: 'Electronics',
            image: '/images/purplegameboy.jpg',
            price: 110,
            brand: 'Wintendo',
            rating: 4.7,
            numReviews: 329,
            description: 'The original Wintendo Gamerboy Color. In purple!',
        },
        {
            _id: '4', 
            name: 'Black Gamerboy',
            category: 'Electronics',
            image: '/images/blackgameboy.jpg',
            price: 120,
            brand: 'Wintendo',
            rating: 4.9,
            numReviews: 516,
            description: 'The original Wintendo Gamerboy Color. In transparent black!',
        },
        {
            _id: '5', 
            name: 'Pokemon Yellow-ish',
            category: 'Electronics',
            image: '/images/pokemonyellow.jpg',
            price: 60,
            brand: 'Wintendo',
            rating: 4.9,
            numReviews: 329,
            description: 'The Wintendo Pokemon Yellow-ish adventure!',
        },
        {
            _id: '6', 
            name: 'Pokemon Emerald-like',
            category: 'Electronics',
            image: '/images/pokemonemerald.jpg',
            price: 75,
            brand: 'Wintendo',
            rating: 4.9,
            numReviews: 148,
            description: 'The Wintendo Pokemon Emerald-like adventure!',
        },
    ]
}
export default data;